name = "zanartu-lavanderia"
main = "worker.js"
compatibility_date = "2026-09-01"

[[d1_databases]]
binding = "DB"
database_name = "zanartu-lavanderia"
database_id = "REEMPLAZAR_CON_DATABASE_ID"

[assets]
directory = "./public"
binding = "ASSETS"
